### ISSUE TITLE
SetX memorized in SetAutoPageBreak

### ISSUE THREAD

**Issue by gubi** [lsolesen/fpdf#13]
By alternating text X position in odd and even pages, the first line is maintained as previous page position.

Note the example:
![schermata del 2016-04-18 17 56 36](https://cloud.githubusercontent.com/assets/746559/14610600/ecd82cf6-058e-11e6-9da9-0eb2c86e28a0.png)

**Comment by lsolesen** [comment]
This is an uofficial repo. You should report it on fpdf.org

Den man. 18. apr. 2016 17.59 skrev Alessandro Gubitosi <
notifications@github.com>:

**Comment by gubi** [comment]
The used code is the following:
```php
$pdf = new PDF();
$pdf->SetDisplayMode("fullpage", "single");
$pdf->SetCreator("ManagR");
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->AddFont("Ubuntu", "", "Ubuntu-R.php");
$pdf->AddFont("Ubuntu", "I", "Ubuntu-RI.php");
$pdf->AddFont("Ubuntu", "B", "Ubuntu-B.php");

$pdf->SetFont('Ubuntu','',12);
for($i=1;$i<=200;$i++) {
    // Document margins
    switch($pdf->PageNo()) {
        case 1:
            $pdf->SetX(40);
            break;
        case 2:
            $pdf->SetX(20);
            break;
        case 3:
            $pdf->SetX(40);
            break;
    }
    $pdf->Cell(0,5,'Printing line number '.$i,1,1, "L");
}
$pdf->Output();
```

**Comment by gubi** [comment]
https://github.com/lsolesen/fpdf/issues/13#issuecomment-211445933

Ok sorry
